name: Java CI with Gradle

# 변경 감지할 브랜치
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

# 실행 내용
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 깃허브 코드 가져오기
      - uses: actions/checkout@v3

      # 2. JDK 환경 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. properties 생성
      - name: make application-test.yml
        run: |
          cd ./src/main/resources
          touch ./application-test.yml
          echo "${{ secrets.YML_TEST }}" > ./application-test.yml

      # 4. gradle 통해 자바 소스 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 5. 도커에 이미지 업로드 (로그인, 이미지 빌드, 푸쉬)
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/taxi .
          docker push ${{ secrets.DOCKER_USERNAME }}/taxi

      # 6. 보안 그룹 ip 추가
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      # 7. 도커 이미지 pull, 실행
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PEM_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/taxi
            docker stop spring-taxi
            docker container prune -f
            docker compose up -d
            docker image prune -a -f

      # 8. 보안 그룹 ip 삭제
      - name: Remove Github Actions IP From Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32